logging:
  level:
    root: debug

google:
  oauth:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI}

naver:
  oauth:
    client-id: ${NAVER_OAUTH_CLIENT_ID}
    client-secret: ${NAVER_OAUTH_CLIENT_SECRET}

kakao:
  oauth:
    client-id: ${KAKAO_OAUTH_CLIENT_ID}
    redirect-uri: ${KAKAO_OAUTH_REDIRECT_URI}

---

spring:
  config:
    activate:
      on-profile: local
    import: classpath:application-secret.yml

---

spring:
  config:
    activate:
      on-profile: test
    import: classpath:application-test.yml